
#ifndef ATMO_ABILITY_HANDLER_H
#define ATMO_ABILITY_HANDLER_H

#include "atmosphere_platform.h"
#include "atmosphere_callbacks.h"

#include "../atmo/core.h"

#ifdef __cplusplus
	extern "C"{
#endif

#define ATMO_ABILITY(ELEMENT, NAME) ATMO_ ## ELEMENT ## _ABILITY_  ## NAME

void ATMO_AbilityHandler(unsigned int abilityHandleId, ATMO_Value_t *value);

#define ATMO_AirQualityCharacteristic_ABILITY_trigger 0x1
#define ATMO_AirQualityCharacteristic_ABILITY_setup 0x2
#define ATMO_AirQualityCharacteristic_ABILITY_setValue 0x3
#define ATMO_AirQualityCharacteristic_ABILITY_written 0x4
#define ATMO_AirQualityCharacteristic_ABILITY_subscibed 0x5
#define ATMO_AirQualityCharacteristic_ABILITY_unsubscribed 0x6
#define ATMO_TemperatureCharacteristic_ABILITY_trigger 0x7
#define ATMO_TemperatureCharacteristic_ABILITY_setup 0x8
#define ATMO_TemperatureCharacteristic_ABILITY_setValue 0x9
#define ATMO_TemperatureCharacteristic_ABILITY_written 0xa
#define ATMO_TemperatureCharacteristic_ABILITY_subscibed 0xb
#define ATMO_TemperatureCharacteristic_ABILITY_unsubscribed 0xc
#define ATMO_HumidityCharacteristic_ABILITY_trigger 0xd
#define ATMO_HumidityCharacteristic_ABILITY_setup 0xe
#define ATMO_HumidityCharacteristic_ABILITY_setValue 0xf
#define ATMO_HumidityCharacteristic_ABILITY_written 0x10
#define ATMO_HumidityCharacteristic_ABILITY_subscibed 0x11
#define ATMO_HumidityCharacteristic_ABILITY_unsubscribed 0x12
#define ATMO_PressureCharacteristic_ABILITY_trigger 0x13
#define ATMO_PressureCharacteristic_ABILITY_setup 0x14
#define ATMO_PressureCharacteristic_ABILITY_setValue 0x15
#define ATMO_PressureCharacteristic_ABILITY_written 0x16
#define ATMO_PressureCharacteristic_ABILITY_subscibed 0x17
#define ATMO_PressureCharacteristic_ABILITY_unsubscribed 0x18
#define ATMO_AmbientLightCharacteristic_ABILITY_trigger 0x19
#define ATMO_AmbientLightCharacteristic_ABILITY_setup 0x1a
#define ATMO_AmbientLightCharacteristic_ABILITY_setValue 0x1b
#define ATMO_AmbientLightCharacteristic_ABILITY_written 0x1c
#define ATMO_AmbientLightCharacteristic_ABILITY_subscibed 0x1d
#define ATMO_AmbientLightCharacteristic_ABILITY_unsubscribed 0x1e
#define ATMO_SX9500Touch_ABILITY_trigger 0x1f
#define ATMO_SX9500Touch_ABILITY_setup 0x20
#define ATMO_SX9500Touch_ABILITY_getTouchData 0x21
#define ATMO_SX9500Touch_ABILITY_pressUp 0x22
#define ATMO_SX9500Touch_ABILITY_pressDown 0x23
#define ATMO_SX9500Touch_ABILITY_pressLeft 0x24
#define ATMO_SX9500Touch_ABILITY_pressRight 0x25
#define ATMO_Temperature_P_ABILITY_trigger 0x26
#define ATMO_Temperature_P_ABILITY_displayPage 0x27
#define ATMO_Temperature_P_ABILITY_onDisplayed 0x28
#define ATMO_Temperature_P_ABILITY_topRightButtonPressed 0x29
#define ATMO_Temperature_P_ABILITY_bottomRightButtonPressed 0x2a
#define ATMO_Temperature_P_ABILITY_topLeftButtonPressed 0x2b
#define ATMO_Temperature_P_ABILITY_bottomLeftButtonPressed 0x2c
#define ATMO_Temperature_P_ABILITY_setup 0x2d
#define ATMO_Temperature_P_ABILITY_onLeave 0x2e
#define ATMO_Temperature_P_ABILITY_setLabel 0x2f
#define ATMO_EmbeddedPageController_ABILITY_trigger 0x30
#define ATMO_EmbeddedPageController_ABILITY_setup 0x31
#define ATMO_EmbeddedPageController_ABILITY_displayRootPage 0x32
#define ATMO_EmbeddedPageController_ABILITY_navigateUp 0x33
#define ATMO_EmbeddedPageController_ABILITY_navigateDown 0x34
#define ATMO_EmbeddedPageController_ABILITY_navigateLeft 0x35
#define ATMO_EmbeddedPageController_ABILITY_navigateRight 0x36
#define ATMO_EmbeddedPageController_ABILITY_processTopRightButton 0x37
#define ATMO_EmbeddedPageController_ABILITY_processBottomRightButton 0x38
#define ATMO_EmbeddedPageController_ABILITY_processTopLeftButton 0x39
#define ATMO_EmbeddedPageController_ABILITY_processBottomLeftButton 0x3a
#define ATMO_Humidity_Pag_ABILITY_trigger 0x3b
#define ATMO_Humidity_Pag_ABILITY_displayPage 0x3c
#define ATMO_Humidity_Pag_ABILITY_onDisplayed 0x3d
#define ATMO_Humidity_Pag_ABILITY_topRightButtonPressed 0x3e
#define ATMO_Humidity_Pag_ABILITY_bottomRightButtonPressed 0x3f
#define ATMO_Humidity_Pag_ABILITY_topLeftButtonPressed 0x40
#define ATMO_Humidity_Pag_ABILITY_bottomLeftButtonPressed 0x41
#define ATMO_Humidity_Pag_ABILITY_setup 0x42
#define ATMO_Humidity_Pag_ABILITY_onLeave 0x43
#define ATMO_Humidity_Pag_ABILITY_setLabel 0x44
#define ATMO_Pressure_Pag_ABILITY_trigger 0x45
#define ATMO_Pressure_Pag_ABILITY_displayPage 0x46
#define ATMO_Pressure_Pag_ABILITY_onDisplayed 0x47
#define ATMO_Pressure_Pag_ABILITY_topRightButtonPressed 0x48
#define ATMO_Pressure_Pag_ABILITY_bottomRightButtonPressed 0x49
#define ATMO_Pressure_Pag_ABILITY_topLeftButtonPressed 0x4a
#define ATMO_Pressure_Pag_ABILITY_bottomLeftButtonPressed 0x4b
#define ATMO_Pressure_Pag_ABILITY_setup 0x4c
#define ATMO_Pressure_Pag_ABILITY_onLeave 0x4d
#define ATMO_Pressure_Pag_ABILITY_setLabel 0x4e
#define ATMO_ConvertPressur_ABILITY_trigger 0x4f
#define ATMO_AmientLight_Pag_ABILITY_trigger 0x50
#define ATMO_AmientLight_Pag_ABILITY_displayPage 0x51
#define ATMO_AmientLight_Pag_ABILITY_onDisplayed 0x52
#define ATMO_AmientLight_Pag_ABILITY_topRightButtonPressed 0x53
#define ATMO_AmientLight_Pag_ABILITY_bottomRightButtonPressed 0x54
#define ATMO_AmientLight_Pag_ABILITY_topLeftButtonPressed 0x55
#define ATMO_AmientLight_Pag_ABILITY_bottomLeftButtonPressed 0x56
#define ATMO_AmientLight_Pag_ABILITY_setup 0x57
#define ATMO_AmientLight_Pag_ABILITY_onLeave 0x58
#define ATMO_AmientLight_Pag_ABILITY_setLabel 0x59
#define ATMO_AirQuality_Pag_ABILITY_trigger 0x5a
#define ATMO_AirQuality_Pag_ABILITY_displayPage 0x5b
#define ATMO_AirQuality_Pag_ABILITY_onDisplayed 0x5c
#define ATMO_AirQuality_Pag_ABILITY_topRightButtonPressed 0x5d
#define ATMO_AirQuality_Pag_ABILITY_bottomRightButtonPressed 0x5e
#define ATMO_AirQuality_Pag_ABILITY_topLeftButtonPressed 0x5f
#define ATMO_AirQuality_Pag_ABILITY_bottomLeftButtonPressed 0x60
#define ATMO_AirQuality_Pag_ABILITY_setup 0x61
#define ATMO_AirQuality_Pag_ABILITY_onLeave 0x62
#define ATMO_AirQuality_Pag_ABILITY_setLabel 0x63
#define ATMO_Interval_ABILITY_trigger 0x64
#define ATMO_Interval_ABILITY_setup 0x65
#define ATMO_Interval_ABILITY_interval 0x66
#define ATMO_TSL2572AmbientLight_ABILITY_trigger 0x67
#define ATMO_TSL2572AmbientLight_ABILITY_setup 0x68
#define ATMO_TSL2572AmbientLight_ABILITY_setEnabled 0x69
#define ATMO_TSL2572AmbientLight_ABILITY_setDisabled 0x6a
#define ATMO_TSL2572AmbientLight_ABILITY_setEnabledDisabled 0x6b
#define ATMO_TSL2572AmbientLight_ABILITY_readAmbientLight 0x6c
#define ATMO_GetTempStr_ABILITY_trigger 0x6d
#define ATMO_GetHumidityStr_ABILITY_trigger 0x6e
#define ATMO_GetPressureStr_ABILITY_trigger 0x6f
#define ATMO_GetLightStr_ABILITY_trigger 0x70
#define ATMO_GetAirQualityStr_ABILITY_trigger 0x71
#define ATMO_ENS210TemperatureHumidity_ABILITY_trigger 0x72
#define ATMO_ENS210TemperatureHumidity_ABILITY_setup 0x73
#define ATMO_ENS210TemperatureHumidity_ABILITY_setEnabled 0x74
#define ATMO_ENS210TemperatureHumidity_ABILITY_setDisabled 0x75
#define ATMO_ENS210TemperatureHumidity_ABILITY_setEnabledDisabled 0x76
#define ATMO_ENS210TemperatureHumidity_ABILITY_readTemperature 0x77
#define ATMO_ENS210TemperatureHumidity_ABILITY_readHumidity 0x78
#define ATMO_MPL3115Pressure_ABILITY_trigger 0x79
#define ATMO_MPL3115Pressure_ABILITY_setup 0x7a
#define ATMO_MPL3115Pressure_ABILITY_setEnabled 0x7b
#define ATMO_MPL3115Pressure_ABILITY_setDisabled 0x7c
#define ATMO_MPL3115Pressure_ABILITY_setEnabledDisabled 0x7d
#define ATMO_MPL3115Pressure_ABILITY_readAltitude 0x7e
#define ATMO_MPL3115Pressure_ABILITY_readPressure 0x7f
#define ATMO_MPL3115Pressure_ABILITY_readPressureKpa 0x80
#define ATMO_CCS811AirQuality_ABILITY_trigger 0x81
#define ATMO_CCS811AirQuality_ABILITY_setup 0x82
#define ATMO_CCS811AirQuality_ABILITY_setEnabled 0x83
#define ATMO_CCS811AirQuality_ABILITY_setDisabled 0x84
#define ATMO_CCS811AirQuality_ABILITY_setEnabledDisabled 0x85
#define ATMO_CCS811AirQuality_ABILITY_readTVOC 0x86
#define ATMO_CCS811AirQuality_ABILITY_readCO2 0x87
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_trigger 0x88
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_setup 0x89
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_setBacklightOff 0x8a
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_setBacklightLow 0x8b
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_setBacklightMedium 0x8c
#define ATMO_EmbeddedNxpRpkBacklight_ABILITY_setBacklightHigh 0x8d
#ifdef __cplusplus
}
#endif
#endif
