
#ifndef ATMO_TRIGGER_HANDLER_H
#define ATMO_TRIGGER_HANDLER_H

#include "atmosphere_platform.h"
#include "../atmo/core.h"

#ifdef __cplusplus
	extern "C"{
#endif

#define ATMO_TRIGGER(ELEMENT, NAME) ATMO_ ## ELEMENT ## _TRIGGER_  ## NAME

void ATMO_TriggerHandler(unsigned int triggerHandleId, ATMO_Value_t *value);

#define ATMO_AirQualityCharacteristic_TRIGGER_triggered 0x1
#define ATMO_AirQualityCharacteristic_TRIGGER_written 0x2
#define ATMO_AirQualityCharacteristic_TRIGGER_subscibed 0x3
#define ATMO_AirQualityCharacteristic_TRIGGER_unsubscribed 0x4
#define ATMO_TemperatureCharacteristic_TRIGGER_triggered 0x5
#define ATMO_TemperatureCharacteristic_TRIGGER_written 0x6
#define ATMO_TemperatureCharacteristic_TRIGGER_subscibed 0x7
#define ATMO_TemperatureCharacteristic_TRIGGER_unsubscribed 0x8
#define ATMO_HumidityCharacteristic_TRIGGER_triggered 0x9
#define ATMO_HumidityCharacteristic_TRIGGER_written 0xa
#define ATMO_HumidityCharacteristic_TRIGGER_subscibed 0xb
#define ATMO_HumidityCharacteristic_TRIGGER_unsubscribed 0xc
#define ATMO_PressureCharacteristic_TRIGGER_triggered 0xd
#define ATMO_PressureCharacteristic_TRIGGER_written 0xe
#define ATMO_PressureCharacteristic_TRIGGER_subscibed 0xf
#define ATMO_PressureCharacteristic_TRIGGER_unsubscribed 0x10
#define ATMO_AmbientLightCharacteristic_TRIGGER_triggered 0x11
#define ATMO_AmbientLightCharacteristic_TRIGGER_written 0x12
#define ATMO_AmbientLightCharacteristic_TRIGGER_subscibed 0x13
#define ATMO_AmbientLightCharacteristic_TRIGGER_unsubscribed 0x14
#define ATMO_SX9500Touch_TRIGGER_triggered 0x15
#define ATMO_SX9500Touch_TRIGGER_touchDataRead 0x16
#define ATMO_SX9500Touch_TRIGGER_upPressed 0x17
#define ATMO_SX9500Touch_TRIGGER_downPressed 0x18
#define ATMO_SX9500Touch_TRIGGER_leftPressed 0x19
#define ATMO_SX9500Touch_TRIGGER_rightPressed 0x1a
#define ATMO_Temperature_P_TRIGGER_triggered 0x1b
#define ATMO_Temperature_P_TRIGGER_onDisplayed 0x1c
#define ATMO_Temperature_P_TRIGGER_topRightButtonPressed 0x1d
#define ATMO_Temperature_P_TRIGGER_bottomRightButtonPressed 0x1e
#define ATMO_Temperature_P_TRIGGER_topLeftButtonPressed 0x1f
#define ATMO_Temperature_P_TRIGGER_bottomLeftButtonPressed 0x20
#define ATMO_Temperature_P_TRIGGER_onLeave 0x21
#define ATMO_EmbeddedPageController_TRIGGER_triggered 0x22
#define ATMO_EmbeddedPageController_TRIGGER_navigateUp 0x23
#define ATMO_EmbeddedPageController_TRIGGER_navigateDown 0x24
#define ATMO_EmbeddedPageController_TRIGGER_navigateLeft 0x25
#define ATMO_EmbeddedPageController_TRIGGER_navigateRight 0x26
#define ATMO_EmbeddedPageController_TRIGGER_processTopRightButton 0x27
#define ATMO_EmbeddedPageController_TRIGGER_processBottomRightButton 0x28
#define ATMO_EmbeddedPageController_TRIGGER_processTopLeftButton 0x29
#define ATMO_EmbeddedPageController_TRIGGER_processBottomLeftButton 0x2a
#define ATMO_Humidity_Pag_TRIGGER_triggered 0x2b
#define ATMO_Humidity_Pag_TRIGGER_onDisplayed 0x2c
#define ATMO_Humidity_Pag_TRIGGER_topRightButtonPressed 0x2d
#define ATMO_Humidity_Pag_TRIGGER_bottomRightButtonPressed 0x2e
#define ATMO_Humidity_Pag_TRIGGER_topLeftButtonPressed 0x2f
#define ATMO_Humidity_Pag_TRIGGER_bottomLeftButtonPressed 0x30
#define ATMO_Humidity_Pag_TRIGGER_onLeave 0x31
#define ATMO_Pressure_Pag_TRIGGER_triggered 0x32
#define ATMO_Pressure_Pag_TRIGGER_onDisplayed 0x33
#define ATMO_Pressure_Pag_TRIGGER_topRightButtonPressed 0x34
#define ATMO_Pressure_Pag_TRIGGER_bottomRightButtonPressed 0x35
#define ATMO_Pressure_Pag_TRIGGER_topLeftButtonPressed 0x36
#define ATMO_Pressure_Pag_TRIGGER_bottomLeftButtonPressed 0x37
#define ATMO_Pressure_Pag_TRIGGER_onLeave 0x38
#define ATMO_ConvertPressur_TRIGGER_triggered 0x39
#define ATMO_AmientLight_Pag_TRIGGER_triggered 0x3a
#define ATMO_AmientLight_Pag_TRIGGER_onDisplayed 0x3b
#define ATMO_AmientLight_Pag_TRIGGER_topRightButtonPressed 0x3c
#define ATMO_AmientLight_Pag_TRIGGER_bottomRightButtonPressed 0x3d
#define ATMO_AmientLight_Pag_TRIGGER_topLeftButtonPressed 0x3e
#define ATMO_AmientLight_Pag_TRIGGER_bottomLeftButtonPressed 0x3f
#define ATMO_AmientLight_Pag_TRIGGER_onLeave 0x40
#define ATMO_AirQuality_Pag_TRIGGER_triggered 0x41
#define ATMO_AirQuality_Pag_TRIGGER_onDisplayed 0x42
#define ATMO_AirQuality_Pag_TRIGGER_topRightButtonPressed 0x43
#define ATMO_AirQuality_Pag_TRIGGER_bottomRightButtonPressed 0x44
#define ATMO_AirQuality_Pag_TRIGGER_topLeftButtonPressed 0x45
#define ATMO_AirQuality_Pag_TRIGGER_bottomLeftButtonPressed 0x46
#define ATMO_AirQuality_Pag_TRIGGER_onLeave 0x47
#define ATMO_Interval_TRIGGER_triggered 0x48
#define ATMO_Interval_TRIGGER_interval 0x49
#define ATMO_TSL2572AmbientLight_TRIGGER_triggered 0x4a
#define ATMO_TSL2572AmbientLight_TRIGGER_ambientLightRead 0x4b
#define ATMO_GetTempStr_TRIGGER_triggered 0x4c
#define ATMO_GetHumidityStr_TRIGGER_triggered 0x4d
#define ATMO_GetPressureStr_TRIGGER_triggered 0x4e
#define ATMO_GetLightStr_TRIGGER_triggered 0x4f
#define ATMO_GetAirQualityStr_TRIGGER_triggered 0x50
#define ATMO_ENS210TemperatureHumidity_TRIGGER_triggered 0x51
#define ATMO_ENS210TemperatureHumidity_TRIGGER_temperatureRead 0x52
#define ATMO_ENS210TemperatureHumidity_TRIGGER_humidityRead 0x53
#define ATMO_MPL3115Pressure_TRIGGER_triggered 0x54
#define ATMO_MPL3115Pressure_TRIGGER_altitudeRead 0x55
#define ATMO_MPL3115Pressure_TRIGGER_pressureRead 0x56
#define ATMO_MPL3115Pressure_TRIGGER_pressureReadKpa 0x57
#define ATMO_CCS811AirQuality_TRIGGER_triggered 0x58
#define ATMO_CCS811AirQuality_TRIGGER_TVOCRead 0x59
#define ATMO_CCS811AirQuality_TRIGGER_CO2Read 0x5a
#define ATMO_EmbeddedNxpRpkBacklight_TRIGGER_triggered 0x5b
#define ATMO_EmbeddedNxpRpkBacklight_TRIGGER_backlightSet 0x5c
#ifdef __cplusplus
}
#endif
#endif
